cloud:
  aws:
    s3:
      bucket: okdkbucket
    stack.auto: false
    regin.static : ap-northeast-2
    credentials:
      accessKey: AKIAYYZ3LSLHREYGWC36
      secretKey: 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